apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplaceapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketplaceapp
  template:
    metadata:
      labels:
        app: marketplaceapp
    spec:
      containers:
        - name: marketplaceapp
          build:
            context: .
            dockerfile: ./Dockerfile
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: marketplaceapp-service
spec:
  selector:
    app: marketplaceapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
