name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Add a debugging step to list files in the repository root
      - name: List files for debugging
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in Root Directory:"
          ls -l
          echo "Files in Marketplace Directory:"
          ls -l Marketplace

      # Build and push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .  # Set the context to the root of the repository
          dockerfile: Marketplace/Dockerfile  # Path to Dockerfile relative to the root
          push: true
          tags: dejans12/marketplaceapp:latest

      # Logout from Docker Hub
      - name: Logout
        run: docker logout
